import type { Metadata } from "next"
import { Archivo, Lato, Geist_Mono } from "next/font/google"
import "./globals.css"
import Footer from "../components/Footer/Footer"
import ScrollToTop from "../components/ScrollToTop"

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
})

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="it"
      className={`${lato.variable} ${archivo.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full bg-black">
        <ScrollToTop />

        <main className="main-bg relative z-10 min-h-screen rounded-b-[42px]">
          {children}
        </main>

        <div className="h-[100vh]" />

        <Footer />
      </body>
    </html>
  )
}